import sys
import uuid
from typing import NoReturn

from google.adk.apps import ResumabilityConfig
from google.adk.sessions import InMemorySessionService
from google.adk.apps import App
from google.adk.runners import Runner

from agents.coordinator_agent import get_coordinator_agent
from services.initialization_service import initialize_application_services
from services.session_content_query import query_agent_responses


def run_onboarding_app(env_flag: str) -> NoReturn:

    # 1. Initialization (Config, Auth, Logger, Trace ID)
    services = initialize_application_services(env_flag)
    logger = services.logger
    llm_model_id = services.llm_model_id

    employee_email = services.trigger_employee_email
    project_id = services.trigger_project_id

    logger.info("Creating centralized SessionService instance.")
    global_session_service = InMemorySessionService()

    logger.info("Creating user login simulation.")


    # 2. Agent Instantiation and A2A Configuration
    logger.info("Setting up hierarchical multi-agent system (A2A).")

    try:

        coordinator_agent = get_coordinator_agent(llm_model_id)


    except Exception as e:
        logger.critical_exception("FATAL: Failed to initialize multi-agent hierarchy.", e)
        sys.exit(1)


    # 3. Application Execution (Runner Setup)
    logger.info("Agent initialization complete. Setting up App Runner for persistence.")

    main_app = App(
        name="OnboardingCoordinatorApp",
        root_agent=coordinator_agent,
        resumability_config=ResumabilityConfig(is_resumable=True)
    )


    runner = Runner(app=main_app, session_service=global_session_service)

    # 4. Simulation of Mission Start
    session_id = f"session_{uuid.uuid4().hex[:8]}"
    mission = f"Start onboarding for Project ID: {project_id}. Employee Email: {employee_email}."
    logger.info(f"Mission received (Jigsaw Trigger Mock): {mission}")

    events = []
    responses = query_agent_responses(events, logger)

    print("\n--- COORDINATOR AGENT RESPONSE ---")
    if responses:
        for response in responses:
            print(f"> AGENT: {response}")
    else:
        print("> AGENT: No final conversational output was generated by the model.")
    print("----------------------------------\n")


    logger.info("Onboarding Mission simulation completed.")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python main.py <env>")
        sys.exit(1)

    env_flag = sys.argv[1]
    run_onboarding_app(env_flag)