from typing import List, Any


def query_agent_responses(events: Any, logger: Any) -> List[str]:
    """
    Queries the Session object to retrieve all conversational text responses
    generated by the Agent (Model role).

    Args:
        events: The Session object returned by the runner.
        logger: The LoggingService instance for structured error reporting.

    Returns:
        A list of clean string responses generated by the Agent.
    """
    agent_messages: List[str] = []

    try:
        for event in events:
            if event.content and event.content.parts:
                for part in event.content.parts:
                    if part.text:
                        agent_messages.append(part.text)

    except Exception as e:
        # Logs the failure to query the session
        logger.error(f"Failed to query session events: {e}", context={"error_type": "SessionContentQueryFailure"})
    return agent_messages